[package]
name = "RECS"
author = "AmaranthineCodices <git@amaranthinecodices.me>"
license = "MIT"
content_root = "src"
version = "1.0.0"

[dependencies]
TestEZ = { git = "https://github.com/Roblox/testez", rev = "master" }
t = { git = "https://github.com/osyrisrblx/t", rev = "master" }
